import express from "express";
import cors from "cors";
import { connectDB } from "./models/connectio.js";
import todosRouter from "./routes/todo.js";
const app = express();
const PORT = process.env.PORT || 4444;
connectDB();
app.use(cors());
app.use(express.json());
app.use("/api/todos", todosRouter);
app.listen(PORT, () => console.log(`Server running localy on on http://localhost:${PORT}`));
